
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2 
  displayName: ".NET Core 3.1.x"
  inputs:
    version: '3.1.x'
    packageType: sdk

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet tool install --global dotnet-ef --version 3.1
  displayName: 'install ef tool'

- script: dotnet ef migrations script -o database.sql --project ./src/maktoob.Persistance/maktoob.Persistance.csproj
  displayName:  'generate database script'

- script: dotnet test --configuration $(buildConfiguration)
  displayName: 'dotnet test $(buildConfiguration)'

- script: dotnet publish -r linux-x64 --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet publish $(BuildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'maktoob'